# Water
block.69=minecraft:water
# Custom light colors
block.100=aether:ambrosium_torch aethersdelight:arkenium_lantern aether:ambrosium_wall_torch minecraft:glowstone aether:quicksoil_glass aether:quicksoil_glass_pane minecraft:cave_vines_plant:berries=true
block.101=minecraft:soul_torch minecraft:soul_wall_torch minecraft:soul_lantern minecraft:soul_campfire:lit=true minecraft:end_portal_frame create_connected:fan_haunting_catalyst
block.102=minecraft:torch minecraft:wall_torch minecraft:lantern minecraft:campfire:lit=true create_connected:fan_smoking_catalyst farmersdelight:stove minecraft:candle minecraft:redstone_lamp:lit=true minecraft:furnace:lit=true minecraft:fire
block.103=minecraft:redstone_torch minecraft:redstone_wall_torch
block.104=tfmg:lithium_torch
block.105=minecraft:enchanting_table
block.106=create:blaze_burner
block.107=powergrid:light_fixture
block.108=minecraft:crying_obsidian
block.109=minecraft:glow_lichen
block.110=minecraft:sea_lantern
block.111=minecraft:ochre_froglight
block.112=minecraft:pearlescent_froglight
block.113=minecraft:verdant_froglight
block.114=minecraft:white_candle:lit=true
block.115=minecraft:light_gray_candle:lit=true
block.116=minecraft:gray_candle:lit=true
block.117=minecraft:black_candle:lit=true
block.118=minecraft:brown_candle:lit=true
block.119=minecraft:red_candle:lit=true
block.120=minecraft:orange_candle:lit=true
block.121=minecraft:yellow_candle:lit=true
block.122=minecraft:lime_candle:lit=true
block.123=minecraft:green_candle:lit=true
block.124=minecraft:cyan_candle:lit=true
block.125=minecraft:light_blue_candle:lit=true
block.126=minecraft:blue_candle:lit=true
block.127=minecraft:purple_candle:lit=true
block.128=minecraft:magenta_candle:lit=true
block.129=minecraft:pink_candle:lit=true
block.130=minecraft:jack_o_lantern burnt:burnt_jack_o_lantern minecraft:shroomlight minecraft:magma_block
block.131=minecraft:end_rod phantasm:purpur_lamp
block.132=minecraft:sculk_sensor:sculk_sensor_phase=active minecraft:calibrated_sculk_sensor:sculk_sensor_phase=active minecraft:sculk_catalyst
block.133=minecraft:small_amethyst_bud minecraft:medium_amethyst_bud minecraft:large_amethyst_bud minecraft:amethyst_cluster
block.134=minecraft:beacon minecraft:nether_star
block.135=minecraft:sea_pickle
block.136=minecraft:lava minecraft:lava_bucket create_connected:fan_blasting_catalyst
block.137=phantasm:void_crystal_block phantasm:void_crystal_tiles phantasm:void_crystal_pillar phantasm:void_crystal_tiles_stairs phantasm:void_crystal_tiles_slab phantasm:crystality phantasm:crystal_glass phantasm:crystal_glass_pane
block.138=phantasm:crystal_block phantasm:crystal_tiles phantasm:crystal_pillar phantasm:crystal_tiles_stairs phantasm:crystal_tiles_slab phantasm:fallen_star phantasm:starflower
block.139=create:experience_block
# Colored translucents (they tint light passing through them)
block.200=minecraft:white_stained_glass minecraft:light_gray_stained_glass minecraft:gray_stained_glass minecraft:black_stained_glass minecraft:brown_stained_glass minecraft:red_stained_glass minecraft:orange_stained_glass minecraft:yellow_stained_glass minecraft:lime_stained_glass minecraft:green_stained_glass minecraft:cyan_stained_glass minecraft:light_blue_stained_glass minecraft:blue_stained_glass minecraft:purple_stained_glass minecraft:magenta_stained_glass minecraft:pink_stained_glass minecraft:white_stained_glass_pane minecraft:light_gray_stained_glass_pane minecraft:gray_stained_glass_pane minecraft:black_stained_glass_pane minecraft:brown_stained_glass_pane minecraft:red_stained_glass_pane minecraft:orange_stained_glass_pane minecraft:yellow_stained_glass_pane minecraft:lime_stained_glass_pane minecraft:green_stained_glass_pane minecraft:cyan_stained_glass_pane minecraft:light_blue_stained_glass_pane minecraft:blue_stained_glass_pane minecraft:purple_stained_glass_pane minecraft:magenta_stained_glass_pane minecraft:pink_stained_glass_pane aether:cold_aercloud aether:blue_aercloud aether:golden_aercloud create:weathered_iron_window create:weathered_iron_window_pane
# Blocks to be ignored by colored lighting
block.201=minecraft:sculk_sensor:sculk_sensor_phase=cooldown,inactive minecraft:calibrated_sculk_sensor:sculk_sensor_phase=cooldown,inactive
# Blocks through which light can pass (without it being tinted)
block.202=minecraft:short_grass minecraft:tall_grass %minecraft:flower_pots %minecraft:fences %minecraft:trapdoors %minecraft:wool_carpets computercraft:cable %computercraft:computer
# Format of passage mask: +X,-X,+Y,-Y,+Z,-Z
# Blocks through which light can pass (passage mask: 000000)
block.1000=
# Blocks through which light can pass (passage mask: 000001)
block.1001=
# ...

layer.translucent=aether:cold_aercloud aether:blue_aercloud aether:golden_aercloud aether:quicksoil_glass aether:quicksoil_glass_pane