oit = true

oit.gbuffers.coefficientRanks = 3

oit.gbuffers.colortex0 = 0

oit.gbuffers.colortex1 = frontmost
oit.gbuffers.colortex1.format = RGBA8

oit.gbuffers.colortex7 = frontmost
oit.gbuffers.colortex7.format = RGBA8