entity.1=minecraft:ghast
entity.100=minecraft:current_player
# Glowing entities (each needs their own ID to match with one color from GLOWING_ENTITY_COLORS)
entity.200=minecraft:glow_squid
entity.300=minecraft:entity_flame