# Items excluded from the enchantment glint outline
item.69=powergrid:copper_coil powergrid:insulated_copper_wire powergrid:wire powergrid:iron_wire powergrid:golden_wire powergrid:copper_cord powergrid:string_light_cord create:experience_nugget
# Armor trims
item.420=trim_amethyst trim_copper trim_diamond trim_emerald trim_gold trim_iron trim_lapis trim_quartz trim_netherite trim_redstone
# Spyglass
item.71=minecraft:spyglass

# Custom light colors (should match the numbers in block.properties)
item.100=aether:ambrosium_torch aethersdelight:arkenium_lantern aether:ambrosium_wall_torch minecraft:glowstone minecraft:glowstone_dust aether:quicksoil_glass aether:quicksoil_glass_pane phantasm:void_crystal_glass phantasm:void_crystal_glass_pane minecraft:glow_berries
item.101=minecraft:soul_torch minecraft:soul_wall_torch minecraft:soul_lantern minecraft:soul_campfire minecraft:end_portal_frame minecraft:glow_ink_sac create_connected:fan_haunting_catalyst
item.102=minecraft:torch minecraft:wall_torch minecraft:lantern minecraft:campfire create_connected:fan_smoking_catalyst farmersdelight:stove minecraft:candle
item.103=minecraft:redstone_torch minecraft:redstone_wall_torch
item.104=tfmg:lithium_torch
item.105=minecraft:enchanting_table
item.106=create:blaze_burner
item.107=powergrid:light_fixture
item.108=minecraft:crying_obsidian
item.109=minecraft:glow_lichen
item.110=minecraft:sea_lantern
item.111=minecraft:ochre_froglight
item.112=minecraft:pearlescent_froglight
item.113=minecraft:verdant_froglight
item.114=minecraft:white_candle
item.115=minecraft:light_gray_candle
item.116=minecraft:gray_candle
item.117=minecraft:black_candle
item.118=minecraft:brown_candle
item.119=minecraft:red_candle
item.120=minecraft:orange_candle
item.121=minecraft:yellow_candle
item.122=minecraft:lime_candle
item.123=minecraft:green_candle
item.124=minecraft:cyan_candle
item.125=minecraft:light_blue_candle
item.126=minecraft:blue_candle
item.127=minecraft:purple_candle
item.128=minecraft:magenta_candle
item.129=minecraft:pink_candle
item.130=minecraft:jack_o_lantern burnt:burnt_jack_o_lantern minecraft:shroomlight minecraft:magma_block
item.131=minecraft:end_rod phantasm:purpur_lamp
item.132=minecraft:sculk_sensor minecraft:calibrated_sculk_sensor minecraft:sculk_catalyst
item.133=minecraft:small_amethyst_bud minecraft:medium_amethyst_bud minecraft:large_amethyst_bud minecraft:amethyst_cluster
item.134=minecraft:beacon minecraft:nether_star
item.135=minecraft:sea_pickle
item.136=minecraft:lava minecraft:lava_bucket minecraft:blaze_rod minecraft:blaze_powder minecraft:fire_charge create_connected:fan_blasting_catalyst
item.137=phantasm:void_crystal_block phantasm:void_crystal_tiles phantasm:void_crystal_pillar phantasm:void_crystal_tiles_stairs phantasm:void_crystal_tiles_slab phantasm:void_crystal_shard phantasm:crystality phantasm:crystal_glass phantasm:crystal_glass_pane
item.138=phantasm:crystal_block phantasm:crystal_tiles phantasm:crystal_pillar phantasm:crystal_tiles_stairs phantasm:crystal_tiles_slab phantasm:fallen_star phantasm:crystal_shard phantasm:starflower
item.139=create:experience_block