# customTexture.lightmap_static = textures/lightmap.png
customTexture.voronoi_3d = textures/voronoi_noise_3d.bin TEXTURE_3D R8 256 256 256 RED UNSIGNED_BYTE
separateAo=true
oldHandLight=false
texture.noise=textures/normals_noise.png
blend.gbuffers_armor_glint=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ZERO
blend.gbuffers_hand.colortex0=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
blend.gbuffers_entities=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
blend.gbuffers_weather=ONE ZERO ONE ZERO
# flip.gbuffers_hand.colortex5=true
rain.depth=false

# Neccessary because Voxy doesn't allow image uniforms in their fragment shaders
bufferObject.0 = 4 true 1.0 1.0

#ifdef DO_COLORED_LIGHTING
iris.features.required=CUSTOM_IMAGES SSBO

#if VOXEL_AREA_SIZE == 128
image.voxel_img=voxel_img_sampler RED_INTEGER R32UI UNSIGNED_INT false false 128 256 128
image.color_img=color_img_sampler RGBA RGBA8 UNSIGNED_BYTE false false 128 128 128
image.color_img_flip=color_img_flip_sampler RGBA RGBA8 UNSIGNED_BYTE false false 128 128 128
#elif VOXEL_AREA_SIZE == 192
image.voxel_img=voxel_img_sampler RED_INTEGER R32UI UNSIGNED_INT false false 192 384 192
image.color_img=color_img_sampler RGBA RGBA8 UNSIGNED_BYTE false false 192 192 192
image.color_img_flip=color_img_flip_sampler RGBA RGBA8 UNSIGNED_BYTE false false 192 192 192
#elif VOXEL_AREA_SIZE == 256
image.voxel_img=voxel_img_sampler RED_INTEGER R32UI UNSIGNED_INT false false 256 512 256
image.color_img=color_img_sampler RGBA RGBA8 UNSIGNED_BYTE false false 256 256 256
image.color_img_flip=color_img_flip_sampler RGBA RGBA8 UNSIGNED_BYTE false false 256 256 256
#endif

# SSBO for entity colored lighting bins (6MiB for 16³ bins with up to 128 * 12B of data each + 16³ times 8B of extra information per bin)
bufferObject.0=6307840

shadow.enabled=true
shadow.culling=reversed

shadowTranslucent=true

occlusion.culling=false
frustum.culling=true

#ifdef DISABLE_BACKFACE_CULLING
backFace.solid=false
#else
backFace.solid=true
#endif

#endif

#ifndef DO_COLORED_LIGHTING
program.prepare.enabled=false
#endif

dhShadow.enabled=false

uniform.bool.shadow_floodfill_player=!firstPersonCamera || hideGUI
uniform.vec4.lod_regular_viewspace_z_vec=vec4(gbufferProjection.2.0, gbufferProjection.2.1, gbufferProjection.2.2, gbufferProjection.2.3)
uniform.vec4.lod_regular_viewspace_w_vec=vec4(gbufferProjection.3.0, gbufferProjection.3.1, gbufferProjection.3.2, gbufferProjection.3.3)

screen = PLAYER_FOV <profile> [WEATHER] [LIGHTING] [FINAL_IMAGE] [DEBUG]
screen.DEBUG = DEBUG_DISPLAY_LIGHT_VOXELS DEBUG_DISPLAY_LIGHT_VOXEL_STRENGTHS DEBUG_ONLY_DISPLAY_LIGHT_VOXELS DEBUG_DISPLAY_FOODFILL DEBUG_DISPLAY_BLOCKLIGHT_COL DEBUG_DISPLAY_VOXEL_SOURCE DEBUG_DISPLAY_VOXEL_INFO DEBUG_DISPLAY_TEXTURE
screen.LIGHTING = DO_COLORED_LIGHTING DISABLE_BACKFACE_CULLING FULL_SHADOW_PASS VOXEL_AREA_SIZE DITHER_LIGHTING DITHERING_REDUCTION LIGHT_DITHERING_MODE LIGHT_POSTERIZATION_COLSPACE LIGHT_PROPAGATION_WORKGROUP_SIZE
screen.FINAL_IMAGE = RESOLUTION_TARGET_MAIN RESOLUTION_TARGET_HAND FINAL_IMAGE_DITHERING_REDUCTION FINAL_IMAGE_STYLE
screen.WEATHER = RAIN_REFRACTION BETA_VOLUMETRIC_CLOUDS

sliders = PLAYER_FOV RESOLUTION_TARGET_MAIN RESOLUTION_TARGET_HAND DITHERING_REDUCTION FINAL_IMAGE_DITHERING_REDUCTION VOXEL_AREA_SIZE

profile.FULL = DO_COLORED_LIGHTING DISABLE_BACKFACE_CULLING VOXEL_AREA_SIZE=256 RAIN_REFRACTION
profile.CL_PERF = DO_COLORED_LIGHTING DISABLE_BACKFACE_CULLING VOXEL_AREA_SIZE=192 RAIN_REFRACTION
profile.CL_MINIMAL = DO_COLORED_LIGHTING !DISABLE_BACKFACE_CULLING VOXEL_AREA_SIZE=128 RAIN_REFRACTION
profile.NO_CL = !DO_COLORED_LIGHTING RAIN_REFRACTION
profile.MINIMAL_PERF = !DO_COLORED_LIGHTING !RAIN_REFRACTION
profile.FACTORY_RESET = 